# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/wind.png

# Content configuration version
version: 2

# Personal info
name: 윤용현
title: 백엔드 엔지니어
email: dragonappear1@gmail.com
website: https://velog.io/@dragonappear
github_username:  dragonappear
linkedin_username: yoonyonghyun

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | 
  비즈니스 관점에서 프로덕트를 성장시키는 것에 관심이 많습니다. 이를 위해 빠르게 기획/개발/테스트/배포하는 능력과 데이터를 활용하여 고객을 이해하는 능력을 쌓고자 노력해왔습니다. 비즈니스는 혼자가 아닌 함께 만들 수 있다고 생각하기에, 팀 구성원들과 적극적으로 소통하고 협업해왔습니다.
  
  기술을 배우는 것을 좋아하고, 기본기를 단단히 하는 것에 관심이 많습니다. 사시사철 바뀌는 IT 기술을 익히고 그와 더불어 개발자의 기본 소양을 쌓기 위해 IT 블로그,책,강의를 보고 학습하는 것을 좋아합니다.


content:
  - title: Work
    layout: list
    content:
      - layout: left
        title: 더블루아워
        sub_title: 백엔드 개발자
        caption: (2022.03.02~2022.10.31)
        additional_links:
          - title:  어플리케이션
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.thebluehour.moccozy
        description: |
          **Tech**
          - 창립 멤버로서 혼자서 9개월 동안 [모꼬지 어플리케이션](https://play.google.com/store/apps/details?id=com.thebluehour.moccozy)에 필요한 모든 IT 서비스(DB, API 서버, 백오피스, AWS) 기획/개발/배포/운영
          - Tech: Java 11, SpringBoot, JPA With QueryDsl, Thymeleaf, MariaDB, JUnit 5, Mockito
          - Ehcache → 약 200% 데이터 조회 속도 개선
          - Prometheus, Grafana → JVM 시스템 모니터링 개발
          - ElasticStack→ 로그 수집 시스템 개발, 분석 및 시각화를 통해 데이터를 보는 기반 구축
          - Github Actions → CI/CD 자동화

          **Business**
          - [대한노인회 경기도경로당광역 지원센터 MOU 체결](http://www.startupdaily.kr/news/articleView.html?idxno=1120)
          - [제 3회 스마트 시니어G 지식인 선발대회 개최 및 API 개발 (약 200개 경로당이 참여한 대회)](https://www.100ssd.co.kr/news/articleView.html?idxno=92681)          

        
  - title: Project 
    layout: list 
    content:
      - layout: left
        border: weak  
        title: SURLF
        caption: (2023.04.05~2023.04.11) 
        additional_links:
          - title:  SURLF github
            icon: fab fa-github
            url: https://github.com/dragonappear/SURLF
        description: |
          - 설명: 하루에 10억건의 트래픽을 수용하는 시스템 디자인, URL 축소 API 및 Tracking 웹서버 프로젝트
          - 역할: 개인 프로젝트 Full-stack
          - 개발 기능: URL 축소 링크 생성, 축소 링크로 Origin URL Redirection, URL Tracking API, 비동기 이벤트 처리
          - 사용 기술: Gradle, Java 17, SpringBoot 3, JUnit 5, Mockito, JPA without QueryDSL, Vue3, Redis, Kafka, ELK
          - 문제 해결: [TroubleShooting](https://github.com/dragonappear/SURLF#troubleshoot)

      - layout: left
        border: weak  
        title: SURLF
        caption: (2023.04.05~2023.04.11) 
        additional_links:
          - title:  SURLF github
            icon: fab fa-github
            url: https://github.com/dragonappear/SURLF
        description: |
          - 설명: 하루에 10억건의 트래픽을 수용하는 시스템 디자인, URL 축소 API 및 Tracking 웹서버 프로젝트
          - 역할: 개인 프로젝트 Full-stack
          - 개발 기능: URL 축소 링크 생성, 축소 링크로 Origin URL Redirection, URL Tracking API, 비동기 이벤트 처리
          - 사용 기술: Gradle, Java 17, SpringBoot 3, JUnit 5, Mockito, JPA without QueryDSL, Vue3, Redis, Kafka, ELK
          - 문제 해결: [TroubleShooting](https://github.com/dragonappear/SURLF#troubleshoot)


  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      2016.02~2022.02 인하대학교 컴퓨터공학과



# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
