# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/wind.png

# Content configuration version
version: 2

# Personal info
name: 윤용현
title: 백엔드 엔지니어
email: dragonappear1@gmail.com
website: https://velog.io/@dragonappear
github_username:  dragonappear
linkedin_username: yoonyonghyun

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  비즈니스 관점에서 프로덕트를 성장시키는 것에 관심이 많습니다. 이를 위해 빠르게 기획/개발/테스트/배포하는 능력과 데이터를 활용하여 고객을 이해하는 능력을 쌓고자 노력해왔습니다. 비즈니스는 혼자가 아닌 함께 만들 수 있다고 생각하기에, 팀 구성원들과 적극적으로 소통하고 협업해왔습니다.
  
  기술을 배우는 것을 좋아하고, 기본기를 단단히 하는 것에 관심이 많습니다. 사시사철 바뀌는 IT 기술을 익히고 그와 더불어 개발자의 기본 소양을 쌓기 위해 IT 블로그,책,강의를 보고 학습하는 것을 좋아합니다.


content:
  - title: Work
    layout: list
    content:
      - layout: left
        title: 더블루아워
        sub_title: 백엔드 개발자
        caption: 2022.03~2022.10
        link_text: 서비스
        additional_links:
          - title:  공식 홈페이지
            icon: fab fa-globe
            url: https://www.moccozy.co.kr

          - title:  어플리케이션
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.thebluehour.moccozy

      - layout: left
        title: 더블루아워
        sub_title: 백엔드 개발자
        caption: 2022.03~2022.10
        link_text: 서비스
        additional_links:
          - title:  공식 홈페이지
            icon: fab fa-globe
            url: https://www.moccozy.co.kr

          - title:  어플리케이션
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.thebluehour.moccozy

        
        
  - title: Project 
    layout: list 
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project


  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      2016.02~2022.02 인하대학교 컴퓨터공학과



# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
